export const TOKEN_LOADING = 'TOKEN_LOADING'
export const TOKEN_SUCCESS = 'TOKEN_SUCCESS'
export const TOKEN_ERROR = 'TOKEN_ERROR'

export const CARDS_LOADING = 'CARDS_LOADING'
export const CARDS_LOAD_SUCCESS = 'CARDS_LOAD_SUCCESS'
export const CARDS_LOAD_ERROR = 'CARDS_LOAD_ERROR'

export const CARD_START_MANAGE = 'CARD_START_MANAGE'
export const CARD_END_MANAGE = 'CARD_END_MANAGE'

export const ADD_CARD_UPDATING = 'ADD_CARD_UPDATING'
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS'
export const ADD_CARD_ERROR = 'ADD_CARD_ERROR'

export const UPDATE_CARD_UPDATING = 'UPDATE_CARD_UPDATING'
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS'
export const UPDATE_CARD_ERROR = 'UPDATE_CARD_ERROR'

export const DELETE_CARD_UPDATING = 'DELETE_CARD_UPDATING'
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS'
export const DELETE_CARD_ERROR = 'DELETE_CARD_ERROR'
